name: Publish to PyPI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish wheels
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      
      - name: Build source and wheel distributions
        run: |
          python -m pip install --upgrade build twine
          python -m build
          twine check --strict dist/*
  
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}