name: Publish to PyPI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish wheels
    runs-on: ubuntu-latest
    steps:
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}